[pytest]

pythonpath = .

testpaths = tests/unit_tests tests/integration_tests
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function

markers =
    asyncio: mark a test as an asynchronous test
    slow: mark test as slow